name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        run: sudo apt install nodejs
      - name: Build and Test
        run: npm install && npx webpack && node dist/util.test.node.js
        working-directory: ${{ runner.workspace }}/map
      